name: Scrape and Notify
on:
  schedule:
    - cron: '0 9 * * *'  # 11h00 en heure de Paris (UTC+2)
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run script
        run: python paris_events_scraper.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
